/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SalaryDetailService } from "../salaryDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SalaryDetailCreateInput } from "./SalaryDetailCreateInput";
import { SalaryDetail } from "./SalaryDetail";
import { SalaryDetailFindManyArgs } from "./SalaryDetailFindManyArgs";
import { SalaryDetailWhereUniqueInput } from "./SalaryDetailWhereUniqueInput";
import { SalaryDetailUpdateInput } from "./SalaryDetailUpdateInput";
import { JobFindManyArgs } from "../../job/base/JobFindManyArgs";
import { Job } from "../../job/base/Job";
import { JobWhereUniqueInput } from "../../job/base/JobWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SalaryDetailControllerBase {
  constructor(
    protected readonly service: SalaryDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalaryDetail })
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSalaryDetail(
    @common.Body() data: SalaryDetailCreateInput
  ): Promise<SalaryDetail> {
    return await this.service.createSalaryDetail({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        currency: true,
        duration: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SalaryDetail] })
  @ApiNestedQuery(SalaryDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salaryDetails(@common.Req() request: Request): Promise<SalaryDetail[]> {
    const args = plainToClass(SalaryDetailFindManyArgs, request.query);
    return this.service.salaryDetails({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        currency: true,
        duration: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalaryDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salaryDetail(
    @common.Param() params: SalaryDetailWhereUniqueInput
  ): Promise<SalaryDetail | null> {
    const result = await this.service.salaryDetail({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        currency: true,
        duration: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalaryDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSalaryDetail(
    @common.Param() params: SalaryDetailWhereUniqueInput,
    @common.Body() data: SalaryDetailUpdateInput
  ): Promise<SalaryDetail | null> {
    try {
      return await this.service.updateSalaryDetail({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          currency: true,
          duration: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalaryDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSalaryDetail(
    @common.Param() params: SalaryDetailWhereUniqueInput
  ): Promise<SalaryDetail | null> {
    try {
      return await this.service.deleteSalaryDetail({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          currency: true,
          duration: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/jobs")
  @ApiNestedQuery(JobFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Job",
    action: "read",
    possession: "any",
  })
  async findJobs(
    @common.Req() request: Request,
    @common.Param() params: SalaryDetailWhereUniqueInput
  ): Promise<Job[]> {
    const query = plainToClass(JobFindManyArgs, request.query);
    const results = await this.service.findJobs(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        experience: true,
        id: true,
        jobType: true,
        redirectionUrl: true,
        role: true,

        salaryDetail: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        vendor: true,
        vendorJobId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/jobs")
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "update",
    possession: "any",
  })
  async connectJobs(
    @common.Param() params: SalaryDetailWhereUniqueInput,
    @common.Body() body: JobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      jobs: {
        connect: body,
      },
    };
    await this.service.updateSalaryDetail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/jobs")
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "update",
    possession: "any",
  })
  async updateJobs(
    @common.Param() params: SalaryDetailWhereUniqueInput,
    @common.Body() body: JobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      jobs: {
        set: body,
      },
    };
    await this.service.updateSalaryDetail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/jobs")
  @nestAccessControl.UseRoles({
    resource: "SalaryDetail",
    action: "update",
    possession: "any",
  })
  async disconnectJobs(
    @common.Param() params: SalaryDetailWhereUniqueInput,
    @common.Body() body: JobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      jobs: {
        disconnect: body,
      },
    };
    await this.service.updateSalaryDetail({
      where: params,
      data,
      select: { id: true },
    });
  }
}
